### ISSUE TITLE
unable to run server

### ISSUE THREAD

**Issue by shaunstanislaus** [jmopr/job-hunter#8]
there isn't a rails config file in your repo, wondering how you run this server?

can't create db, nor migrate data either. could you enlighten me?

**Comment by squanto** [comment]
`/config/database.yml` is git ignored by default. Just make one

I just pulled the repo and ran:

- `bundle install`
  - `brew install postgres` for pg gem
  - `brew install qt5` for capybara-webkit gem

made a 'config/database.yml` with:
```
development:
  database: job_hunter_development
  adapter: postgresql
  host: localhost
```

ran: `rake db:create db:migrate`

And then you should be able to run `rails s` and go to [localhost:3000](localhost:3000)
